version: '3.8'

services:
  kanban-postgres:
    image: "postgres:15-alpine"
    container_name: kanban-postgres
    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanban"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  kanban-app:
    build: 
      context: ./kanban-app
      dockerfile: Dockerfile
    container_name: kanban-app
    environment:
      DB_SERVER: kanban-postgres
    ports:
      - "8080:8080"
    depends_on:
      kanban-postgres:
        condition: service_healthy
    restart: unless-stopped

  kanban-ui:
    build: 
      context: ./kanban-ui
      dockerfile: Dockerfile
    container_name: kanban-ui
    ports:
      - "4200:80"
    depends_on:
      - kanban-app
    restart: unless-stopped


volumes:
  kanban-data:
